apiVersion: v2
name: "cray-hms-reds"
version: 3.0.0
description: "Kubernetes resources for cray-hms-reds"
home: "https://github.com/Cray-HPE/hms-reds-charts"
sources:
  - "https://github.com/Cray-HPE/hms-reds"
dependencies:
  - name: cray-service
    version: "~9.0.0"
    repository: https://artifactory.algol60.net/artifactory/csm-helm-charts
  - name: cray-etcd-base
    version: "~1.0.0"
    repository: https://artifactory.algol60.net/artifactory/csm-helm-charts
maintainers:
  - name: Hardware Management
    url: https://github.com/orgs/Cray-HPE/teams/hardware-management
appVersion: "2.0.0"
annotations:
  artifacthub.io/license: "MIT"
