# Please refer to https://stash.us.cray.com/projects/CLOUD/repos/cray-charts/browse/stable/cray-service/values.yaml?at=refs%2Fheads%2Fmaster
# for more info on values you can set/override
# Note that cray-service.containers[*].image and cray-service.initContainers[*].image map values are one of the only structures that
# differ from the standard kubernetes container spec:
# image:
#   repository: ""
#   tag: "" (default = "latest")
#   pullPolicy: "" (default = "IfNotPresent")

global:
  appVersion: 1.22.0
  #testVersion: 1.22.0
  testVersion: 1.22.0-20220614223047.b889e4c

image:
  repository: artifactory.algol60.net/csm-docker/stable/cray-reds
  pullPolicy: IfNotPresent

tests:
  image:
    repository: artifactory.algol60.net/csm-docker/stable/cray-reds-test
    pullPolicy: Always

# Version of the kubectl pod to use when upgrading/downgrading charts
kubectl:
  image:
    repository: artifactory.algol60.net/csm-docker/stable/docker-kubectl
    tag: 1.19.15
    pullPolicy: IfNotPresent

hms_ca_uri: ""

cray-service:
  type: "Deployment"
  nameOverride: "cray-reds"
  fullnameOverride: "cray-reds"
  serviceAccountName: "jobs-watcher"
  etcdCluster:
    enabled: true
  containers:
    cray-reds:
      name: "cray-reds"
      image:
        repository: artifactory.algol60.net/csm-docker/stable/cray-reds
      env:
        - name: ETCD_HOST
          value: cray-reds-etcd-client
        - name: ETCD_PORT
          value: "2379"
        - name: DATASTORE_URL
          value: $(ETCD_HOST):$(ETCD_PORT)
        - name: HSM_URL
          value: http://cray-smd/hsm/v2
        - name: REDS_BYPASS_SWITCH_BLACKLIST_PANIC
          value: ""
        - name: VAULT_ADDR
          value: "http://cray-vault.vault:8200"
        - name: VAULT_SKIP_VERIFY
          value: "true"
        - name: SLS_ADDR
          value: "cray-sls/v1"
        - name: REDS_SYSLOG_TARG
          value: "rsyslog-aggregator.hmnlb:514"
        - name: REDS_NTP_TARG
          valueFrom:
            configMapKeyRef:
              name: meds-nwproto-info
              key: NTP_HOST
        - name: REDS_CA_URI
          valueFrom:
            configMapKeyRef:
              name: reds-cacert-info
              key: CA_URI
      readinessProbe:
        httpGet:
          port: 8269
          path: /v1/readiness
        initialDelaySeconds: 15
        periodSeconds: 30
      livenessProbe:
        httpGet:
          port: 8269
          path: /v1/liveness
        initialDelaySeconds: 5
        periodSeconds: 10
      command: ["/bin/sh", "-c"]
      args: ["until curl --head localhost:15000 ; do echo Waiting for Sidecar; sleep 3 ; done ; echo Sidecar available; reds $REDS_OPTS $( [ -n \"$HSM_URL\" ] && echo --hsm=$HSM_URL ) --datastore=$DATASTORE_URL -syslog \"$REDS_SYSLOG_TARG\" -ntp \"$REDS_NTP_TARG\" -sls \"$SLS_ADDR\""]
      ports:
        - name: http
          containerPort: 8269
      volumeMounts:
        - name: cray-pki-cacert-vol
          mountPath: /usr/local/cray-pki
  volumes:
    cray-pki-cacert-vol:
      name: cray-pki-cacert-vol
      configMap:
        name: cray-configmap-ca-public-key
  ingress:
    enabled: true
    prefix: "/apis/reds/"
    uri: "/"
