---
apiVersion: batch/v1
kind:       Job
metadata:
  name: cray-reds-vault-loader
spec:
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: "jobs-watcher"
      containers:
        - name: cray-reds-vault-loader
          env:
            - name: VAULT_ADDR
              value: "http://cray-vault.vault:8200"
            - name: VAULT_SKIP_VERIFY
              value: "true"
            - name: VAULT_REDFISH_BMC_DEFAULTS
              valueFrom:
                secretKeyRef:
                  name: cray-reds-credentials
                  key: vault_redfish_defaults
            - name: VAULT_REDFISH_SWITCH_DEFAULTS
              valueFrom:
                secretKeyRef:
                  name: cray-reds-credentials
                  key: vault_switch_defaults
          image: {{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}
          command: ["vault_loader"]
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cray-reds-deleter
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "0"
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: OnFailure
      serviceAccountName: "cray-reds-service-account"
      containers:
        - name: job-deleter
          image: "{{ .Values.kubectl.image.repository }}:{{ .Values.kubectl.image.tag }}"
          imagePullPolicy: "{{ .Values.kubectl.image.pullPolicy }}"
          command:
          - /bin/sh
          - -c
          - set -x;
            echo " Deleteing job cray-reds-vault-loader";
            kubectl -n services delete job cray-reds-vault-loader;
            echo " Deleteing job cray-reds-init";
            kubectl -n services delete job cray-reds-init;
            exit 0
